// Compiles scripts/worker.template.ts + index.html into the single deployable
// worker gizmos-app/src/index.ts.
//
// Why a single generated file: Gizmos' runtime serves the HTML from the worker
// (c.html(...)), and index.html's inline <script> is full of backticks/${...} so
// it can't be a template literal. We base64-encode it (no special chars) and
// inline it as a plain string constant — in ONE file, because the platform's
// loader doesn't reliably resolve relative imports between source files.
//
// Run after ANY edit to index.html OR scripts/worker.template.ts:
//     node scripts/embed.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const html = readFileSync(new URL("index.html", root));
const template = readFileSync(new URL("scripts/worker.template.ts", root), "utf8");
const b64 = html.toString("base64");

// Match the QUOTED placeholder so we only replace the constant, never a mention
// of the token in a comment (String.replace swaps the first occurrence only).
const PLACEHOLDER = '"__INDEX_HTML_B64__"';
if (!template.includes(PLACEHOLDER)) {
  throw new Error('worker.template.ts is missing the ' + PLACEHOLDER + ' placeholder');
}

const header =
  "// AUTO-GENERATED by scripts/embed.mjs from scripts/worker.template.ts + index.html.\n" +
  "// Do NOT edit by hand — edit the template and re-run `node scripts/embed.mjs`.\n";
const out = header + template.replace(PLACEHOLDER, JSON.stringify(b64));

mkdirSync(fileURLToPath(new URL("gizmos-app/src", root)), { recursive: true });
writeFileSync(new URL("gizmos-app/src/index.ts", root), out);

console.log("Wrote gizmos-app/src/index.ts — inlined " + b64.length + " base64 chars from " + html.length + " bytes of index.html");
